name: mpi
channels:
  - pytorch
  - anaconda
  - conda-forge
  - defaults
dependencies:
  - cudatoolkit=11.6
  - matplotlib
  - pytorch=1.12.1
  - torchvision=0.13.1
  - tqdm
  - pip
  - pip:
    - cython
    - scikit-image
    - scipy
    - pillow
    - opencv-python
    - moviepy
    - pyyaml
    - scikit-learn
    - lpips
    - kornia
    - focal_frequency_loss
    - tensorboard
    - transformers
    - tensorflow
    - tensorflow-addons
