name: mpi
channels:
  - nvidia
  - anaconda
  - conda-forge
  - defaults
dependencies:
  - cudatoolkit=11.6
  - matplotlib
  - pytorch=1.12.1
  - torchaudio=0.12.1
  - torchvision=0.13.1
  - pip
  - pip:
    - numpy==1.19
    - scikit-image==0.19.1
    - scipy==1.8.0
    - pillow==9.0.1
    - opencv-python==4.4.0.40
    - tqdm==4.64.0
    - moviepy==1.0.3
    - pyyaml
    - scikit-learn
    - lpips
    - kornia
    - focal_frequency_loss
    - tensorboard
    - transformers
